###服务端口号
server:
  port: 8761
### 基本信息配置

spring:
  application:
    name: readsea-eureka


eureka:
  instance:
    hostname: 127.0.0.1
#      preferIpAddress: true #标记是否使用IP
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    ###因为自己是为注册中心，不需要自己注册自己
#    register-with-eureka: false
#    ###因为自己是为注册中心，不需要检索服务
#    fetch-registry: false
    registerWithEureka: false
    fetchRegistry: false


