spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.230.26:3306/fivebigproject?useSSL=false&&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  mapper-locations: class*:mapper/*.xml
